<a href="https://colab.research.google.com/github/Sihan-A/Pydata_2e_Chinese_Notebook/blob/main/ch05_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas⼊⻔

In [5]:
# clone the book repository
!git clone https://github.com/wesm/pydata-book.git
# move to the directory
%cd /content/pydata-book

Cloning into 'pydata-book'...
remote: Enumerating objects: 447, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 447 (delta 2), reused 6 (delta 2), pack-reused 440
Receiving objects: 100% (447/447), 40.55 MiB | 18.55 MiB/s, done.
Resolving deltas: 100% (139/139), done.
/content/pydata-book


- Numpy: 同质型数值类数据
- Pandas: 表格型或异质型数据

In [6]:
# 导入pandas
import pandas as pd
# 导入Series和DataFrame
from pandas import Series, DataFrame

In [7]:
import numpy as np # 导入numpy
np.random.seed(12345) # reproducibility
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## 5.1 pandas的数据结构介绍

### 5.1.1 Series
Series: 一维数组型对象
- 值序列
- 索引（index）

In [8]:
obj = pd.Series([4, 7, -5, 3]) # 创建Series，拥有默认的index[0,N-1]
obj # 查看

0    4
1    7
2   -5
3    3
dtype: int64

In [9]:
obj.values # values属性

array([ 4,  7, -5,  3])

In [10]:
obj.index  # index属性，like range(4)

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4, 7, -5, 3],
                 index=['d', 'b', 'a', 'c']) # 创建有自定义index的Series
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index # index属性获取index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2['a'] # 使用index来索引

-5

In [14]:
obj2['d'] = 6 # 使用index索引来修改value

In [15]:
obj2[['c', 'a', 'd']] # 导入index的列表来索引

c    3
a   -5
d    6
dtype: int64

- `['c', 'a', 'd']`称为**索引列表**。

In [16]:
obj > 0 # 判断

0     True
1     True
2    False
3     True
dtype: bool

In [17]:
obj2[obj2 > 0] # 使用布尔值数组进行过滤→过滤掉False的选项

d    6
b    7
c    3
dtype: int64

In [18]:
obj2 * 2 # 每个元素乘以常数

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
np.exp(obj2) # 可以用numpy的数学操作：e**每个元素

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
'b' in obj2 # in关键字来进行判断

True

In [21]:
'e' in obj2

False

In [22]:
sdata = {'Ohio'  : 35000, # 创建一个字典
         'Texas' : 71000, 
         'Oregon': 16000, 
         'Utah'  : 5000} 
obj3 = pd.Series(sdata) # 将字典传给Series，创建Pandas的Series类型
obj3 # 查看

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states) # 由列表来改变索引顺序
obj4 # 查看

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

因为California索引不在sdata里，所以value为NaN。

In [24]:
pd.isnull(obj4) # isnull()来判断

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4) # notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull() # isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4 # 自动对齐索引，对应相加。没有共同的index的话value为NaN

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population' # Series的name属性
obj4.index.name = 'state' # Series index的name属性
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # Series index按位置赋值
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [33]:
# 字典创建 DataFrame
# 1. 创建字典
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
# 2. 将字典传入DataFrame
frame = pd.DataFrame(data) 
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [34]:
frame.head() # 显示前5行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
# 指定排列顺序
pd.DataFrame(data,                            # 导入字典
            columns=['year', 'state', 'pop']) # 列索引排序

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [36]:
# 传的列不在字典中，产生缺失值
frame2 = pd.DataFrame(data,\
                      columns=['year', 'state', 'pop', 'debt'], # 列索引排序，debt不在列索引中，出现NaN
                      index=['one', 'two', 'three', 'four','five', 'six']) # index行索引
frame2 # 查看

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [37]:
frame2.columns # 获取列索引

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
frame2['state'] # 字典型标记检索

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [39]:
frame2.year # 属性检索

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [40]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [41]:
frame2.loc['three'] # 行索引：位置或特殊属性loc

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 16.5 # 修改列，传入标量
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [43]:
frame2['debt'] = np.arange(6.) # 修改列，传入值数组
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [44]:
val = pd.Series([-1.2, -1.5, -1.7],            # 创建Series
                index=['two', 'four', 'five']) # index
val # 查看

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [45]:
frame2['debt'] = val # val index里没有one，three和six，所以产生NaN
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [46]:
frame2['eastern'] = frame2.state == 'Ohio' # 添加列，根据判断条件
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [47]:
del frame2['eastern'] # del关键字删除列
frame2.columns # 查看DataFrame的列索引

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},         # 创建嵌套字典
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop) # 导入嵌套字典生成DataFrame
frame3 # 查看
# 列索引：外部字典的keys
# 行索引：内部字典的keys

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [49]:
frame3.T # DataFrame的转置

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [50]:
pd.DataFrame(pop,
            index=[2001, 2002, 2003]) # 行索引排序
# 之前的pop没有2003行索引，所以产生NaN

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [51]:
frame3 # 查看DataFrame

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [52]:
frame3['Ohio'][:-1] # DataFrame列索引生成Series，然后切片

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [53]:
pdata = {'Ohio': frame3['Ohio'][:-1],     # 创建包含Series的字典
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata) # DataFrame导入包含Series的字典

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

| 类型                         | 说明                                                         |
| ---------------------------- | ------------------------------------------------------------ |
| 二维ndarray                  | 数据矩阵，还可以传入行标和列标                               |
| 由数组、列表或元组组成的字典 | 每个序列会变成DataFrame的一列。所有序列的长度必须相同        |
| NumPy的结构化/记录数组       | 类似于“由数组组成的字典”                                     |
| 由Series组成的字典           | 每个Series会成为一列。如果没有显式指定索引，则各Series的索引会被合并成结果的行索引 |
| 由字典组成的字典             | 各内层字典会成为一列。键会被合并成结果的行索引，跟“由Series组成的字典”的情况一样 |
| 字典或Series的列表           | 各项将会成为DataFrame的一行。字典键或Series索引的并集将会成为DataFrame的列标 |
| 由列表或元组组成的列表       | 类似于“二维ndarray“                                          |
| 另一个DataFrame              | 该DataFrame的索引将会被沿用，除非显式指定了其他索引          |
| NumPy的MaskedArray           | 类似于“二维ndarray”的情况，只是掩码值在结果DataFrame会变成NA/缺失值 |

In [54]:
# DataFrame的index和column都有name属性
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [55]:
frame3.values # DataFrame的values属性

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [56]:
frame2 # 查看一下frame2，以便了解下个单元格的操作

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [57]:
frame2.values # 当DataFrame的列是不同的dtype，values会自动选择适合所有列的dtype

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 Index Objects 索引对象

In [58]:
obj = pd.Series(range(3), index=['a', 'b', 'c']) # 创建Series
index = obj.index # 索引对象
index

Index(['a', 'b', 'c'], dtype='object')

In [59]:
index[1:] # 索引对象切片

Index(['b', 'c'], dtype='object')

索引对象是不可变的：
- index[1] = 'd'  # TypeError 报错

In [60]:
labels = pd.Index(np.arange(3)) # 创建索引对象
labels # 查看索引对象

Int64Index([0, 1, 2], dtype='int64')

In [61]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels) # 传入索引对象
obj2 # 查看Series

0    1.5
1   -2.5
2    0.0
dtype: float64

In [62]:
obj2.index is labels # is关键字判断

True

In [63]:
frame3 # 查看DataFrame

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [64]:
frame3.columns # 获取DataFrame列索引，有dtype属性和name属性

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [65]:
'Ohio' in frame3.columns # in关键字判断

True

In [66]:
frame3.index # 获取DataFrame行索引，有dtype属性和name属性

Int64Index([2001, 2002, 2000], dtype='int64', name='year')

In [67]:
2003 in frame3.index # in关键字判断

False

In [68]:
# 索引对象可以有重复index
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar']) # 创建索引对象
dup_labels # 查看索引对象

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing 重建索引

In [69]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],      # 创建Series
                index=['d', 'b', 'a', 'c']) # 设定index
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [70]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # 重建索引reindex，存入obj2变量
obj2 # 查看重建索引后的Series，之前没有'e' index，所以引入缺失值NaN

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [71]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], # 创建Series
                 index=[0, 2, 4])
obj3 # 查看Series

0      blue
2    purple
4    yellow
dtype: object

In [72]:
obj3.reindex(range(6),
             method='ffill') # method = ffill：前向插值
# 之前没有index[1]，所以插入index[0]的值到index[1]

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [73]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), # 创建DataFrame
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame # 查看DataFrame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [74]:
frame2 = frame.reindex(['a', 'b', 'c', 'd']) # 重建索引
frame2 # 查看DataFrame

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [75]:
states = ['Texas', 'Utah', 'California'] # 创建列表
frame.reindex(columns=states) # 重建列索引

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [76]:
# frame.loc[['a','b','c','d'],states] # 报错，不再被支持

In [77]:
frame.reindex(index = ['a', 'b', 'c', 'd'],  # 重建行索引
              columns = states) # 重建列索引

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping Entries from an Axis

In [78]:
obj = pd.Series(np.arange(5.),                    # 创建Series
                index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [79]:
new_obj = obj.drop('c') # 删除'c'单行
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [80]:
obj.drop(['d', 'c']) # 删除'c'和'd'两行

a    0.0
b    1.0
e    4.0
dtype: float64

In [81]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), # 创建DataFrame
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'], # 行索引
                    columns = ['one', 'two', 'three', 'four']) # 列索引
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [82]:
data.drop(['Colorado', 'Ohio']) # 列表传入drop()，删除'Colorado'和'Ohio'两行

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.drop('two', # 删除'two'列
          axis=1) # axis=1或axis='columns'表明列上操作

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [84]:
data.drop(['two', 'four'],
          axis='columns') # 删除'two'和'four'两列

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [85]:
obj # 看一下这个Series，以便理解下面的操作

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [86]:
obj.drop('c', inplace=True) # inplace=True：原地修改，不返回

In [87]:
obj # 查看删除'c'行和inplace=True的Series

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [88]:
obj = pd.Series(np.arange(4.), # 创建Series
                index=['a', 'b', 'c', 'd']) # 设定index
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [89]:
obj['b'] # Series的索引

1.0

In [90]:
obj[1] # 根据索引值：选择第二项

1.0

In [91]:
obj[2:4] # 切片索引

c    2.0
d    3.0
dtype: float64

In [92]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [93]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [94]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [95]:
obj['b':'c'] # Slicing with labels包含尾部

b    1.0
c    2.0
dtype: float64

In [96]:

obj['b':'c'] = 5 # 使用索引index来修改值
obj # 查看修改后的Seires

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [97]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [99]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [100]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [101]:
data['three'] > 5 # 判断

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [102]:
data[data['three'] > 5] # 过滤掉False的行（Ohio行）

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [103]:
data < 5 # 判断

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [104]:
data[data < 5] = 0 # 把所有True的项都改为0
data # 查看修改后的DataFrame

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc
- 轴标签`loc`
- 整数标签`iloc`

In [105]:
data # 查看data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
data.loc['Colorado', ['two', 'three']] # 指定行和列

two      5
three    6
Name: Colorado, dtype: int64

In [107]:
data.iloc[2] # iloc：第三行

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [108]:
data.iloc[2, [3, 0, 1]] # iloc整数标签：2行，[3, 0, 1]列

four    11
one      8
two      9
Name: Utah, dtype: int64

In [109]:
data.iloc[[1,2]] # 第二行和第三行

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [110]:
data.iloc[[1, 2], [3, 0, 1]]
# 在上面cell的基础上，再选择第四列，第一列和第二列

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [111]:
data.loc[:'Utah']
# 'Utah'行及之前的所有行

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11

In [112]:
data.loc[:'Utah', 'two'] # 再上面cell的基础上，再选择'two'列

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [113]:
data.iloc[:, :3] # 先所有行，再前三列

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [114]:
data.iloc[:, :3][data.three > 5] # 在上面cell的基础上，在选择three列里值大于5的行
# Ohio行的three列是2，惨遭过滤

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [115]:
ser = pd.Series(np.arange(3.)) # 创建Series
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [116]:
# ser[-1] 报错，因为ambiguity

In [117]:
ser = pd.Series(np.arange(3.))

In [118]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [119]:
ser2 = pd.Series(np.arange(3.), # 创建Series
                 index=['a', 'b', 'c']) # 指定index
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [120]:
ser2[-1] # 现在可以索引了，没有ambiguity的问题了。Series的最后一项

2.0

In [121]:
ser[:1] # 直接索引第一项，不包含尾部

0    0.0
dtype: float64

In [122]:
ser.loc[:1] # 更准确的索引使用loc或iloc，包含尾部

0    0.0
1    1.0
dtype: float64

In [123]:
ser.iloc[:1] # 整数索引

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [124]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5],
               index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [125]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index = ['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [126]:
s1 + s2 # 没有overlapped index的返回NaN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [127]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                   columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [128]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [129]:
df1 + df2 # 没有overlapped的行和列返回NaN

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [130]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [131]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [132]:
df1 - df2 # 行和列都没有overlap，全部NaN

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [133]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [134]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [135]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [136]:
df1.add(df2, fill_value=0) # df1+df2; 缺失的部分当作是0，然后再做运算

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [137]:
1 / df1 # 1除以df1的每个元素

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [138]:
df1.rdiv(1) # 1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [139]:
df1.div(1) # df1 / 1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [140]:
df1.reindex(columns = df2.columns) # 重建索引

a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

In [141]:
df1.reindex(columns = df2.columns,
            fill_value=0) # fill_value=0：NaN的部分都换成0

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [142]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [143]:
arr[0] # ndarray第一行

array([0., 1., 2., 3.])

In [144]:
arr - arr[0] # NumPy广播机制

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [145]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [146]:
series = frame.iloc[0] # Dataframe第一行，存为series
series # 查看series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [147]:
frame - series # 广播到每个行

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [148]:
series2 = pd.Series(range(3), 
                    index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [149]:
frame + series2 # series多个f index，少个d index，所以这两列都是NaN（没有overlap）

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [150]:
series3 = frame['d'] # 将frame的d列存为series
series3 # 查看

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [151]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [152]:
frame.sub(series3, # frame-series
          axis='index') # 在行上操作

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [153]:
frame = pd.DataFrame(np.random.randn(4, 3),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [154]:
np.abs(frame)

b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [155]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [156]:
frame.apply(f, axis='columns')

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [157]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [158]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [159]:
frame['e'].map(format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

### Sorting and Ranking

In [160]:
obj = pd.Series(range(4), # 创建Series
                index=['d', 'a', 'b', 'c']) # index
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [161]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), # 创建DataFrame
                     index=['three', 'one'], # 行索引
                     columns=['d', 'a', 'b', 'c']) # 列索引
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [162]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [163]:
frame.sort_index(axis=1, ascending=False) # 列上操作；降序

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [164]:
obj = pd.Series([4, 7, -3, 2]) # 创建Series
obj.sort_values() 

2   -3
3    2
0    4
1    7
dtype: int64

In [165]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2]) # 创建有NaN的Series
obj.sort_values() # 排序value；NaN会排在最后面

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [166]:
frame = pd.DataFrame({'b': [4, 7, -3, 2],
                      'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [167]:
frame.sort_values(by='b') # 根据b列的value来排序

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [168]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [169]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [170]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [171]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [172]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [173]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [174]:
obj.index.is_unique

False

In [175]:
obj['a']
obj['c']

4

In [176]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df
df.loc['b']

0         1         2
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

## Summarizing and Computing Descriptive Statistics

In [177]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [178]:
df.sum() # 在列上各行的总和

one    9.25
two   -5.80
dtype: float64

In [179]:
df.sum(axis='columns') # 在行上各列的总和

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [180]:
df.mean(axis='columns', # 在行上各列的总和
        skipna=False) # 不忽略NaN

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [181]:
df.idxmax() # 各列上最大值的index

one    b
two    d
dtype: object

In [182]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [183]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [184]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

conda install pandas-datareader

In [185]:
!git clone https://github.com/wesm/pydata-book.git

fatal: destination path 'pydata-book' already exists and is not an empty directory.


In [186]:
price = pd.read_pickle('/content/pydata-book/examples/yahoo_price.pkl')
volume = pd.read_pickle('/content/pydata-book/examples/yahoo_volume.pkl')

import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [187]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [188]:
returns['MSFT'].corr(returns['IBM'])

0.49976361144151144

In [189]:
returns['MSFT'].cov(returns['IBM'])

8.870655479703546e-05

In [190]:
returns.MSFT.corr(returns.IBM)

0.49976361144151144

In [191]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [192]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [193]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [194]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### Unique Values, Value Counts, and Membership

In [195]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [196]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [197]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [198]:
pd.value_counts(obj.values,
                sort = False)

d    1
b    2
c    3
a    3
dtype: int64

In [199]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [200]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [201]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [202]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [203]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [204]:
data.apply(pd.value_counts)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [205]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## Conclusion

In [206]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS